name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  check-code-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dev tools
        run: |
          pip install -e .[dev]

      - name: Check code format with Black
        run: |
          black --check .

      - name: Check code style with Flake8
        if: ${{ always() }}
        run: |
          flake8 .

  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install module
        run: |
          sudo apt-get install libportaudio2 -y
          pip install wheel
          pip install -e .[dev]
          
      - name: Run tests
        run: |
          make run-tests

      - name: Run e2e tests
        run: |
          make run-e2e-tests
